<a href="https://colab.research.google.com/github/sufand/ExchangeRates/blob/main/FX_YahooFinance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [98]:
import os
import time
import datetime
import pandas as pd
path = "C:\\Documenti\\"

In [72]:
valuta = 'EURUSD=X'
data_inizio = int(time.mktime(datetime.datetime(2021, 1, 1).timetuple()))
data_fine = int(time.mktime(datetime.datetime(2022, 1, 1).timetuple()))
frequenza = '1d'

In [73]:
query = f'https://query1.finance.yahoo.com/v7/finance/download/{valuta}?period1={data_inizio}&period2={data_fine}&interval={frequenza}&events=history&includeAdjustedClose=true'

In [20]:
print(query)

https://query1.finance.yahoo.com/v7/finance/download/EURUSD=X?period1=1609459200&period2=1640995200&interval=1d&events=history&includeAdjustedClose=true

In [74]:
USD = pd.read_csv(query)
USD.head(20)

          Date      Open      High       Low     Close  Adj Close  Volume
0   2021-01-01  1.217285  1.221699  1.213499  1.218027   1.218027       0
1   2021-01-04  1.224905  1.230999  1.217137  1.225070   1.225070       0
2   2021-01-05  1.225295  1.229483  1.224995  1.225160   1.225160       0
3   2021-01-06  1.229861  1.235025  1.226693  1.230027   1.230027       0
4   2021-01-07  1.233776  1.234568  1.224665  1.234111   1.234111       0
5   2021-01-08  1.226873  1.228215  1.221493  1.227144   1.227144       0
6   2021-01-11  1.218784  1.219959  1.213474  1.218621   1.218621       0
7   2021-01-12  1.216160  1.217849  1.213887  1.216070   1.216070       0
8   2021-01-13  1.220927  1.222494  1.215539  1.220889   1.220889       0
9   2021-01-14  1.216175  1.217285  1.211314  1.216249   1.216249       0
10  2021-01-15  1.215300  1.216249  1.208474  1.215126   1.215126       0
11  2021-01-18  1.206724  1.208620  1.205545  1.206811   1.206811       0
12  2021-01-19  1.207846  1.214491  1.207846  1.207729   1.207729       0
13  2021-01-20  1.213946  1.216001  1.207773  1.213887   1.213887       0
14  2021-01-21  1.211534  1.217196  1.210991  1.211563   1.211563       0
15  2021-01-22  1.216619  1.218800  1.215200  1.216629   1.216629       0
16  2021-01-25  1.216856  1.218600  1.211725  1.216945   1.216945       0
17  2021-01-26  1.214329  1.217500  1.210844  1.214624   1.214624       0
18  2021-01-27  1.216323  1.217137  1.206200  1.216299   1.216299       0
19  2021-01-28  1.210478  1.214400  1.208240  1.210507   1.210507       0

In [103]:
USD.to_csv("C:/Documenti/USD.csv")

FileNotFoundError: ignored